version: '2'

services:
  vue :
    build: ./vue
    container_name: vue
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - 80:3000
    volumes:
      - ./vue:/vue
      - vue_node_modules:/vue/node_modules

volumes:
  vue_node_modules:
