version: '2'

services:
  # web:
  #   build: ./web
  #   container_name: web
  #   ports:
  #     - 5000:5dcd000
  #   volumes:
  #     - ./web:/web
  #     - web_node_modules:/web/node_modules

  vue :
    build: ./vue
    container_name: vue
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - 80:3000
    volumes:
      - ./vue:/vue
      - vue_node_modules:/vue/node_modules

volumes:
  web_node_modules:
  vue_node_modules:
